from idlecolours import printc
from idlecolours import brown
import time
endconvo = False
print('Well done, you worked out that Harrow killed Viren.')
time.sleep(1.5)
print('His best friend trying to stop his plans to overthrow the king, took things too far. Such a sad ending to a wonderful friendship, dont you think?')
time.sleep(1)
print('Oh well, onto the next dream.')
time.sleep(1.5)
print('This dream will tell you the second piece of information that you need, the location...')
time.sleep(2)
printc(brown('In this dream, you see Viren in the halls of the Manor, running away from something. Then appears Harrow, running past you and towards him with a knife.'))
time.sleep(1.5)
printc(brown('You turn around to see where they are going, but you dont see them, instead, you see that the door at the back is open, so you go in.'))
time.sleep(1.5)
printc(brown("In this room that you have walked into, you see a sink and a bathtub. 'This is the bathroom!' you think to yourself. Then you see another door, opened just wide enough that you see a bed, but nothing else."))
time.sleep(1.5)
printc(brown('Just as you open the door, blood starts pouring into the bathroom. Then you wake up'))
time.sleep(1)
print('Wow, such an intense dream. Hope it wasnt too scary.')
time.sleep(1.5)
print('Do you know where Viren was killed?')
qn = str(input('Y/N '))
if qn.upper() == 'Y':
    print('So where was he killed?')
    time.sleep(1)
    print('A) The bathroom')
    print('B) Virens bedroom')
    print('C) Sorens bedroom')
    print('D) The living room')
    qn = str(input())
    if qn == 'B':
        import Weapon
    else:
        print('Oops, wrong answer. Heres another dream to help you work it out')
        time.sleep(2)
        printc(brown('Here, you are wondering around the manor'))
        time.sleep(1.5)
        printc(brown('Suddenly, hear something coming from one of the bedrooms. You are not sure which one, you so go to see where it might be coming from.'))
        time.sleep(1.5)
        printc(brown("As you go closer to Viren's and Soren's bedroom (two seperate rooms), the sound becomes louder. It seems to be Viren screaming"))
        time.sleep(1.5)
        printc(brown("You are now in front of the bedrooms, but you can't tell where it's coming from."))
        time.sleep(1.5)
        printc(brown('Then, just when someone is coming out of the room, you wake up.'))
        time.sleep(1)
        print('I wonder where the sound is coming from. Do you know?')
        qn = str(input('Y/N'))
        if qn.upper() == 'Y':
            print('Where do you think the sound is coming from?')
            time.sleep(1)
            print('A) Sorens bedroom')
            print('B) The living room')
            print('C) Virens bedroom')
            print('D) The bathroom')
            qn = str(input())
            if qn.upper() == 'C':
                import Weapon
            else:
                print('Oops, wrong answer. Heres another dream to help you work it out')
                time.sleep(2)
                printc(brown('In this dream, you see a trail of blood leading somewhere. You decide to follow it.'))
                time.sleep(1.5)
                printc(brown('As you follow it, you see Harrow walking out of an unknown room in all black, clearly trying to seem anonymous. You also see that the blood trail starts at the room Harrow left.'))
                time.sleep(1.5)
                printc(brown("You run towards the room Harrow left and slowly open the door, where you see Viren's body on the ground and a small table with a picutre of him and his family on it."))
                time.sleep(1.5)
                printc(brown('Then you wake up.'))
                time.sleep(1)
                print('Hmm...I wonder what room that is. Can you tell?')
                qn = str(input('Y/N'))
                if qn.upper() == 'Y':
                    print('What room do you think it is?')
                    time.sleep(1)
                    print('A) The bathroom')
                    print('B) Sorens bedroom')
                    print('C) The living room')
                    print('D) Virens bedroom')
                    qn = str(input())
                    if qn.upper() == 'D':
                        import Weapon
                    else:
                        print('Oops, wrong person.')
                        time.sleep(1)
                        print('Unfortunately you have no more dreams left...')
                        time.sleep(1)
                        print('...so that means that you lost the game and Virens ghost will haunt you.')
                        time.sleep(1.5)
                        print('By the way, do you know who I am?')
                        time.sleep(1.5)
                        print("I'm Viren of course!")
                        time.sleep(1)
                        print('Good luck with having the burden of my murder on you. Hahahaha 😈')
                elif qn.upper() =='N':
                    print('Unfortunately you have no more dreams left...')
                    time.sleep(1)
                    print('...so that means that you lost the game and Virens ghost will haunt you.')
                    time.sleep(1.5)
                    print('By the way, do you know who I am?')
                    time.sleep(1.5)
                    print("I'm Viren of course!")
                    time.sleep(1)
                    print('Good luck with having the burden of my murder on you. Hahahaha 😈')
        elif qn.upper() == 'N':
            print('Heres one last dream to help you work it out')
            time.sleep(2)
            printc(brown('In this dream, you see a trail of blood leading somewhere. You decide to follow it.'))
            time.sleep(1.5)
            printc(brown('As you follow it, you see Harrow walking out of an unknown room in all black, clearly trying to seem anonymous. You also see that the blood trail starts at the room Harrow left.'))
            time.sleep(1.5)
            printc(brown("You run towards the room Harrow left and slowly open the door, where you see Viren's body on the ground and a small table with a picutre of him and his family on it."))
            time.sleep(1.5)
            printc(brown('Then you wake up.'))
            time.sleep(1)
            print('Hmm...I wonder what room that is. Can you tell?')
            qn = str(input('Y/N'))
            if qn.upper == 'Y':
                print('Where do you think the sound is coming from?')
                time.sleep(1)
                print('A) The bathroom')
                print('B) Sorens bedroom')
                print('C) The living room')
                print('D) Virens bedroom')
                qn = str(input())
                if qn.upper() == 'D':
                    import Weapon
                else:
                    print('Oops, wrong person.')
                    time.sleep(1)
                    print('Unfortunately you have no more dreams left...')
                    time.sleep(1)
                    print('...so that means that you lost the game and Virens ghost will haunt you.')
                    time.sleep(1.5)
                    print('By the way, do you know who I am?')
                    time.sleep(1.5)
                    print("I'm Viren of course!")
                    time.sleep(1)
                    print('Good luck with having the burden of my murder on you. Hahahaha 😈')
            elif qn.upper() =='N':
                print('Unfortunately you have no more dreams left...')
                time.sleep(1)
                print('...so that means that you lost the game and Virens ghost will haunt you.')
                time.sleep(1.5)
                print('By the way, do you know who I am?')
                time.sleep(1.5)
                print("I'm Viren of course!")
                time.sleep(1)
                print('Good luck with having the burden of my murder on you. Hahahaha 😈')
elif qn.upper() == 'N':
    print('Heres another dream to help you work it out')
    time.sleep(2)
    printc(brown('Here, you are wondering around the manor'))
    time.sleep(1.5)
    printc(brown('Suddenly, hear something coming from one of the bedrooms. You are not sure which one, you so go to see where it might be coming from.'))
    time.sleep(1.5)
    printc(brown("As you go closer to Viren's and Soren's bedroom (two seperate rooms), the sound becomes louder. It seems to be Viren screaming"))
    time.sleep(1.5)
    printc(brown("You are now in front of the bedrooms, but you can't tell where its coming from."))
    time.sleep(1.5)
    printc(brown('Then, just when someone is coming out of the room, you wake up.'))
    time.sleep(1)
    print('I wonder where the sound is coming from. Do you know?')
    qn = str(input('Y/N'))
    if qn.upper() == 'Y':
        print('Where do you think the sound is coming from?')
        time.sleep(1)
        print('A) Sorens bedroom')
        print('B) The living room')
        print('C) Virens bedroom')
        print('D) The bathroom')
        qn = str(input())
        if qn.upper() == 'C':
            import Weapon
        else:
            print('Oops, wrong answer. Heres another dream to help you work it out')
            time.sleep(2)
            printc(brown('In this dream, you see a trail of blood leading somewhere. You decide to follow it.'))
            time.sleep(1.5)
            printc(brown('As you follow it, you see Harrow walking out of an unknown room in all black, clearly trying to seem anonymous. You also see that the blood trail starts at the room Harrow left.'))
            time.sleep(1.5)
            printc(brown("You run towards the room Harrow left and slowly open the door, where you see Viren's body on the ground and a small table with a picutre of him and his family on it."))
            time.sleep(1.5)
            printc(brown('Then you wake up.'))
            time.sleep(1)
            print('Hmm...I wonder what room that is. Can you tell?')
            qn = str(input('Y/N'))
            if qn.upper == 'Y':
                print('Where do you think the sound is coming from?')
                time.sleep(1)
                print('A) The bathroom')
                print('B) Sorens bedroom')
                print('C) The living room')
                print('D) Virens bedroom')
                qn = str(input())
                if qn.upper() == 'D':
                    import Weapon
                else:
                    print('Sorry, wrong person.')
                    time.sleep(1)
                    print('Unfortunately you have no more dreams left...')
                    time.sleep(1)
                    print('...so that means that you lost the game and Virens ghost will haunt you.')
                    time.sleep(1.5)
                    print('By the way, do you know who I am?')
                    time.sleep(1.5)
                    print("I'm Viren of course!")
                    time.sleep(1)
                    print('Good luck with having the burden of my murder on you. Hahahaha 😈')
            elif qn.upper() =='N':
                print('Unfortunately you have no more dreams left...')
                time.sleep(1)
                print('...so that means that you lost the game and Virens ghost will haunt you.')
                time.sleep(1.5)
                print('By the way, do you know who I am?')
                time.sleep(1.5)
                print("I'm Viren of course!")
                time.sleep(1)
                print('Good luck with having the burden of my murder on you. Hahahaha 😈')
    elif qn.upper() == 'N':
        print('Heres one last dream to help you work it out')
        time.sleep(2)
        printc(brown('In this dream, you see a trail of blood leading somewhere. You decide to follow it.'))
        time.sleep(1.5)
        printc(brown('As you follow it, see Harrow walking out of an unknown room in all black, clearly trying to seem anonymous. You also see that the blood trail starts at the room Harrow left.'))
        time.sleep(1.5)
        printc(brown("You run towards the room Harrow left and slowly open the door, where you see Viren's body on the ground and a small table with a picutre of him and his family on it."))
        time.sleep(1.5)
        printc(brown('Then you wake up.'))
        time.sleep(1)
        print('Hmm...I wonder what room that is. Can you tell?')
        qn = str(input('Y/N'))
        if qn.upper == 'Y':
            print('Where do you think the sound is coming from?')
            time.sleep(1)
            print('A) The bathroom')
            print('B) Sorens bedroom')
            print('C) The living room')
            print('D) Virens bedroom')
            qn = str(input())
            if qn.upper() == 'D':
                import Weapon
            else:
                print('Oops, wrong person.')
                time.sleep(1)
                print('Unfortunately you have no more dreams left...')
                time.sleep(1)
                print('...so that means that you lost the game and Virens ghost will haunt you.')
                time.sleep(1.5)
                print('By the way, do you know who I am?')
                time.sleep(1.5)
                print("I'm Viren of course!")
                time.sleep(1)
                print('Good luck with having the burden of my murder on you. Hahahaha 😈')
        elif qn.upper() =='N':
            print('Unfortunately you have no more dreams left...')
            time.sleep(1)
            print('...so that means that you lost the game and Virens ghost will haunt you.')
            time.sleep(1.5)
            print('By the way, do you know who I am?')
            time.sleep(1.5)
            print("I'm Viren of course!")
            time.sleep(1)
            print('Good luck with having the burden of my murder on you. Hahahaha 😈')
    
            
                
                

                
                
                
                 
               
