import time
from idlecolours import printc
from idlecolours import red
print('Congrats, you have managed to work out that Viren was killed in his bedroom. What a terrible place to be killed, at the place that he rests. Well, if you find this last piece of information, he will be able to rest.')
time.sleep(1.5)
print('Now, this dream will tell you what Harrow used to kill Viren.')
time.sleep(1.5)
print('This is the last piece of information that you need to solve this crime and become free of Virens ghost, good luck working it out ;)')
time.sleep(2)
printc(red('In this dream, you are staring at a painting of Viren and Harrow, where Harrow has his sword on his back and Viren is weaponless.'))
time.sleep(1.5)
printc(red('On the corner of the painting, you see something clearly stuck onto the painting.'))
time.sleep(1.5)
printc(red('You try to take it off, but it is almost impossible to pull it off in one piece.'))
time.sleep(1.5)
printc(red('Eventually, you manage to take the thing off. It seems to be a note.'))
time.sleep(1.5)
printc(red("The note says, 'The thing you are looking for is not in this picture. Or any of the other pictures in this hallway.' You look at the other paintings in the hallway"))
time.sleep(1.5)
printc(red('The painting next to the one in front of you shows Viren holding his sword, and the one after that shows Soren holding his dagger.'))
time.sleep(1.5)
printc(red("A million questions come to your head, but before any of them can be answer, you wake up."))
time.sleep(1)
print('What a weird dream, can you work out the weapon from that dream?')
qn = str(input('Y/N '))
if qn.upper() == 'Y':
    print('What do you think it is?')
    time.sleep(1)
    print('A) Virens sword')
    print('B) Harrows sword')
    print('C) Lissas bow and arrow')
    print('D) Virens pistol')
    qn = str(input())
    if qn.upper() == 'D':
        print('Well done, you have solved the mysterious case of Viren...')
        time.sleep(1.5)
        print('...meaning that Virens ghost wont haunt you for the rest of eternity!!!')
        time.sleep(1.5)
        print('Before I go, do you want to know who I am and how I know so much about this case?')
        qn = str(input('Y/N '))
        if qn.upper() == 'Y':
            print('Well Im Viren of course! You solved my murder!')
            time.sleep(1.5)
            print('Now I can rest while my former best friend rots in prison. Have nice dreams tonight 😈')
        elif qn.upper() == 'N':
            print('Aw, how sad. Anyways, see you in your dreams tonight 😈')
            time.sleep(1.5)
            print('Just kidding...or am I?')
    else:
        print('Oops, wrong weapon. Heres another dream to help you work it out, think carefully.')
        time.sleep(2)
        printc(red('You stand in the centre of Virens bedroom, where you see the different weapons placed in the room.'))
        time.sleep(1.5)
        printc(red('Next to his bed, you see his sword. Near his door, you see Lissas bow and arrow and you see Harrows sword next to the window. On his bed you see the pistol.'))
        time.sleep(1.5)
        printc(red('You bring them all together and notice that two of them have blood on them. The pistol and the arrow from the bow and arrow.'))
        time.sleep(1.5)
        printc(red('You examine the arrow and the pistol. You work out (using your incredible knowledge of blood) that the blood on the arrow is not the same as the blood on the pistol, but you cant tell which one has Virens blood on it.'))
        time.sleep(1.5)
        printc(red('You close your eyes and smell both of them. One of them has animal blood and the other, which is still in your hand, smells like human blood.'))
        time.sleep(1.5)
        printc(red('As you open your eyes, you wake up.'))
        time.sleep(1)
        print('Wow, I guess your weird knowledge about blood came to use. Can you work out the weapon used?')
        qn = str(input('Y/N '))
        if qn.upper() == 'Y':
            print('What do you think it is?')
            time.sleep(1)
            print('A) Virens sword')
            print('B) Harrows sword')
            print('C) Lissas bow and arrow')
            print('D) Virens pistol')
            qn = str(input())
            if qn.upper() == 'D':
                print('Well done, you have solved the mysterious case of Viren...')
                time.sleep(1.5)
                print('...meaning that Virens ghost wont haunt you for the rest of eternity!!!')
                time.sleep(1.5)
                print('Before I go, do you want to know who I am and how I know so much about this case?')
                qn = str(input('Y/N '))
                if qn.upper() == 'Y':
                    print('Well Im Viren of course! You solved my murder!')
                    time.sleep(1.5)
                    print('Now I can rest while my former best friend rots in prison. Have nice dreams tonight 😈')
                elif qn.upper() == 'N':
                    print('Aw, how sad. Anyways, see you in your dreams tonight 😈')
                    time.sleep(1.5)
                    print('Just kidding...or am I?')
            else:
                print('Wrong again. Come on, think really hard. Heres one last dream for you.')
                time.sleep(2)
                printc(red('Here, you are watching Harrow get ready to kill Viren. He puts on all the black clothes he can find and puts on his hoodie.'))
                time.sleep(1.5)
                printc(red('Then he looks at himself in the mirror, then he looks down at his dressing table. You cant see what he is looking at.'))
                time.sleep(1.5)
                printc(red('After a while, you see him put something from his dressing table in his pocket. It doesnt seem to be too big and something tells you thats the weapon.'))
                time.sleep(1.5)
                printc(red('Unfortunately, you cant see it clearly, but it almost looks like the shape of a gun.'))
                time.sleep(1.5)      
                printc(red('As Harrow leaves his room, you wake up.'))
                time.sleep(1)
                print('I wonder what that thing was. Do you know?')
                qn = str(input('Y/N' ))
                if qn.upper() == 'Y':
                    print('What do you think it is?')
                    time.sleep(1)
                    print('A) Virens sword')
                    print('B) Harrows sword')
                    print('C) Lissas bow and arrow')
                    print('D) Virens pistol')
                    qn = str(input())
                    if qn.upper() == 'D':
                        print('Well done, you have solved the mysterious case of Viren...')
                        time.sleep(1.5)
                        print('...meaning that Virens ghost wont haunt you for the rest of eternity!!!')
                        time.sleep(1.5)
                        print('Before I go, do you want to know who I am and how I know so much about this case?')
                        qn = str(input('Y/N '))
                        if qn.upper() == 'Y':
                            print('Well Im Viren of course! You solved my murder!')
                            time.sleep(1.5)
                            print('Now I can rest while my former best friend rots in prison. Have nice dreams tonight 😈')
                        elif qn.upper() == 'N':
                            print('Aw, how sad. Anyways, see you in your dreams tonight 😈')
                            time.sleep(1.5)
                            print('Just kidding...or am I?')
                    else:
                        print('Unfortunately you have no more dreams left...')
                        time.sleep(1)
                        print('...so that means that you lost the game and Virens ghost will haunt you.')
                        time.sleep(1.5)
                        print('By the way, do you know who I am?')
                        time.sleep(1.5)
                        print('Im Viren of course!')
                        time.sleep(1)
                        print('Good luck with having the burden of my murder on you. Hahahaha 😈')
                elif qn.upper() == 'N':
                    print('Unfortunately you have no more dreams left...')
                    time.sleep(1)
                    print('...so that means that you lost the game and Virens ghost will haunt you.')
                    time.sleep(1.5)
                    print('By the way, do you know who I am?')
                    time.sleep(1.5)
                    print('Im Viren of course!')
                    time.sleep(1)
                    print('Good luck with having the burden of my murder on you. Hahahaha 😈')
        elif qn.upper() == 'N':    
            print('Come on, think really hard. Heres one last dream for you.')
            time.sleep(2)
            printc(red('Here, you are watching Harrow get ready to kill Viren. He puts on all the black clothes he can find and puts on his hoodie.'))
            time.sleep(1.5)
            printc(red('Then he looks at himself in the mirror, then he looks down at his dressing table. You cant see what he is looking at.'))
            time.sleep(1.5)
            printc(red('After a while, you see him put something from his dressing table in his pocket. It doesnt seem to be too big and something tells you thats the weapon.'))
            time.sleep(1.5)
            printc(red('Unfortunately, you cant see it clearly, but it almost looks like the shape of a gun.'))
            time.sleep(1.5)      
            printc(red('As Harrow leaves his room, you wake up.'))
            time.sleep(1)
            print('I wonder what that thing was. Do you know?')
            qn = str(input('Y/N '))
            if qn.upper() == 'Y':
                print('What do you think it is?')
                time.sleep(1)
                print('A) Virens sword')
                print('B) Harrows sword')
                print('C) Lissas bow and arrow')
                print('D) Virens pistol')
                qn = str(input())
                if qn.upper() == 'D':
                    print('Well done, you have solved the mysterious case of Viren...')
                    time.sleep(1.5)
                    print('...meaning that Virens ghost wont haunt you for the rest of eternity!!!')
                    time.sleep(1.5)
                    print('Before I go, do you want to know who I am and how I know so much about this case?')
                    qn = str(input('Y/N '))
                    if qn.upper() == 'Y':
                        print('Well Im Viren of course! You solved my murder!')
                        time.sleep(1.5)
                        print('Now I can rest while my former best friend rots in prison. Have nice dreams tonight 😈')
                    elif qn.upper() == 'N':
                        print('Aw, how sad. Anyways, see you in your dreams tonight 😈')
                        time.sleep(1.5)
                        print('Just kidding...or am I?')
                else:
                    print('Unfortunately you have no more dreams left...')
                    time.sleep(1)
                    print('...so that means that you lost the game and Virens ghost will haunt you.')
                    time.sleep(1.5)
                    print('By the way, do you know who I am?')
                    time.sleep(1.5)
                    print('Im Viren of course!')
                    time.sleep(1)
                    print('Good luck with having the burden of my murder on you. Hahahaha 😈')
            elif qn.upper() == 'N':
                print('Unfortunately you have no more dreams left...')
                time.sleep(1)
                print('...so that means that you lost the game and Virens ghost will haunt you.')
                time.sleep(1.5)
                print('By the way, do you know who I am?')
                time.sleep(1.5)
                print('Im Viren of course!')
                time.sleep(1)
                print('Good luck with having the burden of my murder on you. Hahahaha 😈')
elif qn.upper() == 'N':
    print('Heres another dream to help you work it out, think carefully.')
    time.sleep(2)
    printc(red('You stand in the centre of Virens bedroom, where you see the different weapons placed in the room.'))
    time.sleep(1.5)
    printc(red('Next to his bed, you see his sword. Near his door, you see Lissas bow and arrow and you see Harrows sword next to the window. On his bed you see the pistol.'))
    time.sleep(1.5)
    printc(red('You bring them all together and notice that two of them have blood on them. The pistol and the arrow from the bow and arrow.'))
    time.sleep(1.5)
    printc(red('You examine the arrow and the pistol. You work out (using your incredible knowledge of blood) that the blood on the arrow is not the same as the blood on the pistol, but you cant tell which one has Virens blood on it.'))
    time.sleep(1.5)
    printc(red('You close your eyes and smell both of them. One of them has animal blood and the other, which is still in your hand, smells like human blood.'))
    time.sleep(1.5)
    printc(red('As you open your eyes, you wake up.'))
    time.sleep(1)
    print('Wow, I guess your weird knowledge about blood came to use. Can you work out the weapon used?')
    qn = str(input('Y/N '))
    if qn.upper() == 'Y':
        print('What do you think it is?')
        time.sleep(1)
        print('A) Virens sword')
        print('B) Harrows sword')
        print('C) Lissas bow and arrow')
        print('D) Virens pistol')
        qn = str(input())
        if qn.upper() == 'D':
            print('Well done, you have solved the mysterious case of Viren...')
            time.sleep(1.5)
            print('...meaning that Virens ghost wont haunt you for the rest of eternity!!!')
            time.sleep(1.5)
            print('Before I go, do you want to know who I am and how I know so much about this case?')
            qn = str(input('Y/N '))
            if qn.upper() == 'Y':
                print('Well Im Viren of course! You solved my murder!')
                time.sleep(1.5)
                print('Now I can rest while my former best friend rots in prison. Have nice dreams tonight 😈')
            elif qn.upper() == 'N':
                print('Aw, how sad. Anyways, see you in your dreams tonight 😈')
                time.sleep(1.5)
                print('Just kidding...or am I?')
        else:
            print('Wrong again. Come on, think really hard. Heres one last dream for you.')
            time.sleep(2)
            printc(red('Here, you are watching Harrow get ready to kill Viren. He puts on all the black clothes he can find and puts on his hoodie.'))
            time.sleep(1.5)
            printc(red('Then he looks at himself in the mirror, then he looks down at his dressing table. You cant see what he is looking at.'))
            time.sleep(1.5)
            printc(red('After a while, you see him put something from his dressing table in his pocket. It doesnt seem to be too big and something tells you thats the weapon.'))
            time.sleep(1.5)
            printc(red('Unfortunately, you cant see it clearly, but it almost looks like the shape of a gun.'))
            time.sleep(1.5)      
            printc(red('As Harrow leaves his room, you wake up.'))
            time.sleep(1)
            print('I wonder what that thing was. Do you know?')
            qn = str(input('Y/N '))
            if qn.upper() == 'Y':
                print('What do you think it is?')
                time.sleep(1)
                print('A) Virens sword')
                print('B) Harrows sword')
                print('C) Lissas bow and arrow')
                print('D) Virens pistol')
                qn = str(input())
                if qn.upper() == 'D':
                    print('Well done, you have solved the mysterious case of Viren...')
                    time.sleep(1.5)
                    print('...meaning that Virens ghost wont haunt you for the rest of eternity!!!')
                    time.sleep(1.5)
                    print('Before I go, do you want to know who I am and how I know so much about this case?')
                    qn = str(input('Y/N '))
                    if qn.upper() == 'Y':
                        print('Well Im Viren of course! You solved my murder!')
                        time.sleep(1.5)
                        print('Now I can rest while my former best friend rots in prison. Have nice dreams tonight 😈')
                    elif qn.upper() == 'N':
                        print('Aw, how sad. Anyways, see you in your dreams tonight 😈')
                        time.sleep(1.5)
                        print('Just kidding...or am I?')
                else:
                    print('Unfortunately you have no more dreams left...')
                    time.sleep(1)
                    print('...so that means that you lost the game and Virens ghost will haunt you.')
                    time.sleep(1.5)
                    print('By the way, do you know who I am?')
                    time.sleep(1.5)
                    print('Im Viren of course!')
                    time.sleep(1)
                    print('Good luck with having the burden of my murder on you. Hahahaha 😈')
            elif qn.upper() == 'N':
                print('Unfortunately you have no more dreams left...')
                time.sleep(1)
                print('...so that means that you lost the game and Virens ghost will haunt you.')
                time.sleep(1.5)
                print('By the way, do you know who I am?')
                time.sleep(1.5)
                print('Im Viren of course!')
                time.sleep(1)
                print('Good luck with having the burden of my murder on you. Hahahaha 😈')
    elif qn.upper() == 'N':    
        print('Come on, think really hard. Heres one last dream for you.')
        time.sleep(2)
        printc(red('Here, you are watching Harrow get ready to kill Viren. He puts on all the black clothes he can find and puts on his hoodie.'))
        time.sleep(1.5)
        printc(red('Then he looks at himself in the mirror, then he looks down at his dressing table. You cant see what he is looking at.'))
        time.sleep(1.5)
        printc(red('After a while, you see him put something from his dressing table in his pocket. It doesnt seem to be too big and something tells you thats the weapon.'))
        time.sleep(1.5)
        printc(red('Unfortunately, you cant see it clearly, but it almost looks like the shape of a gun.'))
        time.sleep(1.5)      
        printc(red('As Harrow leaves his room, you wake up.'))
        time.sleep(1)
        print('I wonder what that thing was. Do you know?')
        qn = str(input('Y/N '))
        if qn.upper() == 'Y':
            print('What do you think it is?')
            time.sleep(1)
            print('A) Virens sword')
            print('B) Harrows sword')
            print('C) Lissas bow and arrow')
            print('D) Virens pistol')
            qn = str(input())
            if qn.upper() == 'D':
                print('Well done, you have solved the mysterious case of Viren...')
                time.sleep(1.5)
                print('...meaning that Virens ghost wont haunt you for the rest of eternity!!!')
                time.sleep(1.5)
                print('Before I go, do you want to know who I am and how I know so much about this case?')
                qn = str(input('Y/N '))
                if qn.upper() == 'Y':
                    print('Well Im Viren of course! You solved my murder!')
                    time.sleep(1.5)
                    print('Now I can rest while my former best friend rots in prison. Have nice dreams tonight 😈')
                elif qn.upper() == 'N':
                    print('Aw, how sad. Anyways, see you in your dreams tonight 😈')
                    time.sleep(1.5)
                    print('Just kidding...or am I?')
            else:
                print('Unfortunately you have no more dreams left...')
                time.sleep(1)
                print('...so that means that you lost the game and Virens ghost will haunt you.')
                time.sleep(1.5)
                print('By the way, do you know who I am?')
                time.sleep(1.5)
                print('Im Viren of course!')
                time.sleep(1)
                print('Good luck with having the burden of my murder on you. Hahahaha 😈')
        elif qn.upper() == 'N':
            print('Unfortunately you have no more dreams left...')
            time.sleep(1)
            print('...so that means that you lost the game and Virens ghost will haunt you.')
            time.sleep(1.5)
            print('By the way, do you know who I am?')
            time.sleep(1.5)
            print('Im Viren of course!')
            time.sleep(1)
            print('Good luck with having the burden of my murder on you. Hahahaha 😈')
    
            
                 
            
        
